sudo: false

dist: bionic

language: node_js
node_js:
  - '12'

# https://github.com/cypress-io/cypress/issues/4069
addons:
  apt:
    packages:
      - libgconf-2-4
  chrome: stable

cache:
  directories:
    - ~/.cache
    - node_modules

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn --frozen-lockfile --non-interactive --no-progress

script:
  # lint
  - yarn run demo:lint:check
  - yarn run prettier:check
  # tests
  - yarn run readme:check
  - yarn run lib:test:ci
  # build
  - yarn run lib:build:prod:view-engine
  - yarn run demo:build:prod --progress=false --base-href "https://cloudnc.github.io/ngx-sub-form/"
  # e2e tests
  - sed -i 's/<base href="https:\/\/cloudnc.github.io\/ngx-sub-form\/">/<base href="\/">/g' dist/ngx-sub-form-demo/index.html
  - nohup http-server-spa ./dist/ngx-sub-form-demo index.html 4765 &
  - sleep 5
  - yarn run demo:test:e2e:ci
  - sed -i 's/<base href="\/">/<base href="https:\/\/cloudnc.github.io\/ngx-sub-form\/">/g' dist/ngx-sub-form-demo/index.html
  # copy the readme so it can be accessible from npm
  - cp README.md LICENSE dist/ngx-sub-form

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn semantic-release
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: dist/ngx-sub-form-demo
    on:
      branch: master
